In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#load stop words
import codecs

from hazm import Normalizer
l = []
with  open('persian-stopwords-master/persian', encoding='utf-8') as f:
    for w in f.readlines():
        l.append(w.replace('\n',''))


len(l)

1316

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer( stop_words=l)
X = vectorizer.fit_transform(df[df.columns[-1]] )

In [ ]:
from sklearn.decomposition import TruncatedSVD
ncomp=32
svd = TruncatedSVD(n_components=ncomp,algorithm='arpack', random_state=42)
dimX = svd.fit_transform(X)

In [ ]:
from sklearn.cluster import KMeans
nc=20
losses = []

kmeans = KMeans(n_clusters=nc, random_state=0).fit(dimX)

kmeans.score(dimX)

In [ ]:
from sklearn.pipeline import Pipeline
pipe = Pipeline([('vectorizer', vectorizer), ('dimenstionality_reduction', svd) , 
                ('clustering' , kmeans)])

## Hashing

In [10]:
df = pd.read_csv('Fulldocumentword1.csv' , header=None , usecols=[15])
df.head()

15
0  ['کرونا', 'اینجا', 'کرونا', 'اونجا', 'کرونا', ...
1  ['کرونا', 'اینجا', 'کرونا', 'اونجا', 'کرونا', ...
2  ['کرونا', 'اینجا', 'کرونا', 'اونجا', 'کرونا', ...
3  ['کرونا', 'اینجا', 'کرونا', 'اونجا', 'کرونا', ...
4  ['کرونا', 'اینجا', 'کرونا', 'اونجا', 'کرونا', ...

In [15]:
df[15].values.shape

(96024,)

In [30]:
from sklearn.feature_extraction.text import HashingVectorizer
vecHash = HashingVectorizer(stop_words=l)
X = vecHash.fit_transform(df[15].values)

c:\users\lion\appdata\local\programs\python\python37\lib\site-packages\sklearn\feature_extraction\text.py:386: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['آسانی', 'آسیب', 'اثر', 'احیانا', 'اخیرا', 'ازاین', 'اسلامی', 'اطلاعند', 'الاسف', 'البت', 'الظاهر', 'بااین', 'بازی', 'باوجودی', 'برآن', 'برنامه', 'بسته', 'بطوری', 'بفهمی', 'تازگی', 'تحریم', 'تدریج', 'ترتیب', 'تردید', 'ترند', 'تصریحا', 'تفاوتند', 'تند', 'توؤما', 'تول', 'تک', 'تی', 'ثالثا', 'ثانی', 'جمع', 'جمله', 'جنس', 'جوری', 'حاشیه', 'حسابی', 'حکما', 'خارج', 'خسته', 'خوبی', 'خودبه', 'خودی', 'داند', 'دراین', 'درحالی', 'درشتی', 'درصورتی', 'درعین', 'درپی', 'دسته', 'دلخواه', 'دنبال', 'دیوانه', 'ذاتا', 'ذلک', 'راجع', 'رسد', 'رغم', 'رود', 'روزه', 'روشنی', 'زده', 'زودی', 'ساده', 'سادگی', 'سازهاست', 'سالم', 'ساله', 'ست', 'سرعت', 'سمت', 'سه', 'سهوا', 'سیاه', 'شاأالله', 'شدت', 'صریحا', 'صندوق', 'ضد', 'ضمنا', 'طبق', 'طوری', 'عل', 'علاوه', 'علنا', 'علی', 'عملی', 'عینا', '

In [18]:
X.shape

(96024, 1048576)

In [31]:
ex = X[0].todense()
ex[np.where(X[0].todense()>0)] , np.where(X[0].todense()>0)

(matrix([[0.21821789, 0.21821789, 0.21821789]]),
 (array([0, 0, 0], dtype=int64), array([ 13289, 248001, 679369], dtype=int64)))

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer( stop_words=l)
X = vectorizer.fit_transform(df[15].values )

In [20]:
X.shape

(96024, 31914)

In [29]:
# ex = X[0].todense()
# ex[np.where(X[0].todense()>0)] , np.where(X[0].todense()>0)

(matrix([[0.37852048, 0.45889546, 0.62161508, 0.3381635 , 0.25453595,
          0.28388166]]),
 (array([0, 0, 0, 0, 0, 0], dtype=int64),
  array([ 1138,  4099, 14192, 18955, 25693, 29658], dtype=int64)))

In [95]:
from sklearn.feature_extraction.text import CountVectorizer
CountVectorizer.partial_fit = partial_fit
vectorizer = CountVectorizer(stop_words=l)
X = vectorizer.fit_transform(df[15].values[0:100])

In [69]:
X.shape

(100, 119)

In [96]:
len(vectorizer.vocabulary_)

119

In [91]:
def partial_fit(self , data):
    vocab = self.vocabulary_
    self.fit(data)
    vocab = list(set(vocab.keys()).union(set(self.vocabulary_ )))
    self.vocabulary_ = {vocab[i] : i for i in range(len(vocab))}
                 

In [98]:


vectorizer.partial_fit(df[15].values[100:200])
len(vectorizer.vocabulary_)

422

In [83]:
vectorizer.get_params(df[15].values[100:200])


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [59]:
vectorizer2 = CountVectorizer(stop_words=l)
vectorizer2.set_params(**vectorizer.get_params())
X2 = vectorizer2.fit_transform(df[15].values[100:200])

In [60]:
X2.shape

(100, 371)

In [55]:
X3 =vectorizer2.transform(df[15].values[0:1000])

(1000, 371)